stages:
  - build
  - push
  - deploy

variables:
  VERSION: $CI_COMMIT_REF_SLUG
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Image:
  stage: build
  tags: [ shell ]
  script: make image

Push:
  stage: push
  tags: [ shell ]
  only: [ tags, master, develop ]
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script: make deploy

DeployTest:
  stage: deploy
  tags: [ docker ]
  only: [ develop ]
  image:
    name: dockercloud/cli
    entrypoint: ["/bin/sh", "-c"]
  script:
    - docker-cloud stack redeploy ${DOCKERCLOUD_STACK_TEST}
