stages:
  - build
  - push
  - deploy

variables:
  VERSION: $CI_COMMIT_REF_SLUG
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Image:
  stage: build
  tags: [ shell ]
  script: make image

Push:
  stage: push
  tags: [ shell ]
  only: [ tags, master, develop ]
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script: make deploy

Deploy:
  stage: deploy
  tags: [ docker ]
  only: [ master ]
  except: [ manual ]
  image:
    name: dockercloud/cli
    entrypoint: ["/bin/sh", "-c"]
  script:
    - docker-cloud stack redeploy ${DOCKERCLOUD_STACK}

DeployAndImport:
  stage: deploy
  tags: [ docker ]
  only: [ master ]
  when: manual
  image:
    name: dockercloud/cli
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - docker-cloud stack redeploy ${DOCKERCLOUD_STACK} --sync --not-reuse-volumes
  script:
    - export CONTAINER_ID=$(docker-cloud container ps --service search -s Running -q)
    - docker-cloud container exec ${CONTAINER_ID} ./import_scripts/run.sh
