module.exports = {
  'NEO4J_HOST': 'localhost',
  'NEO4J_USER': 'neo4j',
  'NEO4J_PASS': '',
  // 'ES_HOST': 'https://elastic:x5MGQIVk2JLUPoA6kbhmMcpL@015f115508e0b40a70e330aea47f406f.eu-west-1.aws.found.io',
  // 'ES_PORT': 9243,
  'ES_HOST': 'http://localhost',
  'ES_PORT': 9200,
  'ES_INDEX_USER': 'search',
  'ES_INDEX_PROFESSION': 'profession',
  'ES_INDEX_SKILL': 'skill',
  'MYSQL_HOST': 'mysql-clone',
  'MYSQL_PORT': 33060,
  'MYSQL_USER': 'user',
  'MYSQL_PWD': 'password',
  'MYSQL_DB': 'the-dots',
}
