version: "3.3"
services:
  neo4j:
    image: neo4j:3.3.1
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none
    volumes:
      - "neodata:/data"
      - "importdata:/var/lib/neo4j/import"
    ports:
      - "7474:7474"
      - "7687:7687"

  node:
    build: .
    container_name: api
    volumes:
      - "importdata:/data"
    ports:
      - "3000:3000"
    depends_on:
      - neo4j

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "esdata1:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "esdata2:/usr/share/elasticsearch/data"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    container_name: kibana
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  neodata:
  importdata:
  esdata1:
  esdata2:
