version: "3.3"
services:
  neo4j:
    image: neo4j:3.3
    volumes:
      - "/data"
      - "./import_data:/import"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
