build:
	node 0-0-create-csvs.js
	node 1-1-create-user-index.js
	node 1-2-import-users.js
	node 1-3-create_following_relationships.js
	node 2-1-create-professions-index.js
	node 2-2-import-professions.js
	node 2-3-create-user-professions-relationships.js
	node 2-4-send-professions-to-es-from-neo.js
	node 3-1-create-skills-index.js
	node 3-2-import-skills.js
	node 3-3-create-user-skills-relationships.js
	node 3-4-send-skills-to-es-from-neo.js
	node 9-9-send-users-to-es-from-neo.js

